CRITICAL - 2020-04-06 00:03:40 --> Undefined index: id
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 00:05:04 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\dawah\system\Database\MySQLi\Connection.php(330): mysqli->query('INSERT INTO `us...')
#1 C:\xampp\htdocs\dawah\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\dawah\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2206): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\dawah\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(109): CodeIgniter\Model->save(Array)
#7 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#8 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2020-04-06 00:09:11 --> syntax error, unexpected ';', expecting ')'
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('authcontroller/...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('authcontroller/...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 00:17:23 --> Cannot use object of type App\Models\UserModel as array
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 00:19:29 --> Trying to get property 'insert_id' of non-object
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 00:19:54 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 00:23:41 --> array_keys() expects parameter 1 to be array, object given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'array_keys() ex...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): array_keys(Object(App\Models\UserModel))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 00:27:38 --> Undefined property: App\Controllers\AuthController::$db
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 10:55:58 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:06:21 --> Undefined variable: db
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:06:45 --> Undefined variable: db
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:10:36 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert_id()
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 11:18:33 --> Undefined index: my_sqli
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:19:26 --> Cannot use object of type mysqli as array
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 11:20:09 --> Undefined index: mysqli
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:21:08 --> Undefined index: insertID
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:22:03 --> Undefined index: *insertID
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:23:19 --> Undefined offset: 13
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:26:49 --> Undefined offset: 0
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:27:01 --> syntax error, unexpected '0' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('authcontroller/...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('authcontroller/...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:27:26 --> Trying to get property 'table' of non-object
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(107): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:28:59 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(111): CodeIgniter\Model->save(Array)
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-04-06 11:30:08 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(111): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:30:40 --> syntax error, unexpected '$userRolesModel' (T_VARIABLE)
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('authcontroller/...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('authcontroller/...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:30:55 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(112): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:32:09 --> Undefined property: App\Controllers\AuthController::$input
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(110): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 110, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:32:32 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::set()
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 11:32:57 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(111): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:51:29 --> Too few arguments to function CodeIgniter\Model::save(), 0 passed in C:\xampp\htdocs\dawah\app\Controllers\AuthController.php on line 112 and exactly 1 expected
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(112): CodeIgniter\Model->save()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:51:50 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(112): CodeIgniter\Model->insert()
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:52:42 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\system\Model.php(550): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(111): CodeIgniter\Model->save(Array)
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-04-06 11:54:55 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(115): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:57:22 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(112): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 11:59:36 --> Using $this when not in object context
#0 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(108): setRole(71, 'student')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 11:59:49 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\dawah\system\Database\BaseBuilder.php(2191): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\dawah\system\Model.php(722): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\dawah\app\Helpers\roles_helper.php(36): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\dawah\app\Controllers\AuthController.php(108): setRole(72, 'student')
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\AuthController->register()
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#6 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-04-06 20:04:29 --> Too few arguments to function App\Controllers\ClassesController::storeEnrollement(), 0 passed in C:\xampp\htdocs\dawah\system\CodeIgniter.php on line 910 and exactly 2 expected
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 20:11:02 --> Too few arguments to function App\Controllers\ClassesController::storeEnrollement(), 0 passed in C:\xampp\htdocs\dawah\system\CodeIgniter.php on line 910 and exactly 1 expected
#0 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement()
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-04-06 20:11:58 --> Trying to get property 'leave_at' of non-object
#0 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(226): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 226, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:14:14 --> Trying to get property 'user_id' of non-object
#0 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(227): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 227, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:14:50 --> {0, string} route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\dawah\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\dawah\system\Common.php(798): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(275): redirect('http://localhos...')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 20:15:00 --> {0, string} route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\dawah\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\dawah\system\Common.php(798): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(275): redirect('http://localhos...')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#5 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-04-06 20:22:00 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:22:15 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:23:51 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:24:56 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:25:24 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:25:58 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:26:17 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(250): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:31:27 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(253): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:31:45 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(253): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:33:02 --> Array to string conversion
#0 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(249): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 249, Array)
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:33:52 --> syntax error, unexpected 'if' (T_IF)
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('ClassesControll...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('ClassesControll...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:34:07 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(253): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:36:16 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:36:44 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:37:37 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('ClassesControll...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('ClassesControll...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:37:38 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'
#0 C:\xampp\htdocs\dawah\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('ClassesControll...')
#1 C:\xampp\htdocs\dawah\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('ClassesControll...')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-04-06 20:37:59 --> Argument 1 passed to CodeIgniter\Model::doProtectFields() must be of the type array, string given, called in C:\xampp\htdocs\dawah\system\Model.php on line 832
#0 C:\xampp\htdocs\dawah\system\Model.php(832): CodeIgniter\Model->doProtectFields('dd')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array, 'dd')
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:44:43 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:49:57 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-04-06 20:50:15 --> There is no data to {0}.
#0 C:\xampp\htdocs\dawah\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dawah\app\Controllers\ClassesController.php(251): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dawah\system\CodeIgniter.php(910): App\Controllers\ClassesController->storeEnrollement('1')
#3 C:\xampp\htdocs\dawah\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ClassesController))
#4 C:\xampp\htdocs\dawah\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dawah\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
